### PR TITLE
Add RU region

### PR DESCRIPTION
**Pull request by exstrim401**

### CODE REVIEW

**Review by TheShawnMiranda — CHANGES_REQUESTED** [review]
@exstrim401 , to add changes that are not within North America, please add a different file, like list-RU for the RU region. And please make sure these are actual addresses, instead of just swapping ruc instead of aic and ru instead of us.

**Comment by exstrim401** [comment]
I got those addresses from DNS log
What about to split lists to common to all regions and region specific (us, ru)?

**Comment by exstrim401** [comment]
Also there are some domain blocks that do more harm like developers.google.com, ngfts.lge.com (app icons in store), img.nvidiagrid.net (geforce now game logos. without that domain there will be game list without images)

**Comment by exstrim401** [comment]
To be honest
```
||lgtviot.com^
||lgtvcommon.com^
||emp.lgsmartplatform.com^
||ibs.lgappstv.com^
||lgsmartad.com^
||www.ueiwsp.com
```
is enough to block all LG ads and recommendations on any region I guess

**Comment by TheShawnMiranda** [comment]
> I got those addresses from DNS log What about to split lists to common to all regions and region specific (us, ru)?

I'd leave "list" as is, because splitting it now would create a breaking change and add additional setup for US users. Feel free to ad a separate file for other countries or regions. Let list be the common + US file. Other regions can have their own.

> Also there are some domain blocks that do more harm like developers.google.com, ngfts.lge.com (app icons in store), img.nvidiagrid.net (geforce now game logos. without that domain there will be game list without images)

Yes, I don't use the store and I don't use Nvidia's streaming service. Look at the readme.

> To be honest
> 
> ```
> ||lgtviot.com^
> ||lgtvcommon.com^
> ||emp.lgsmartplatform.com^
> ||ibs.lgappstv.com^
> ||lgsmartad.com^
> ||www.ueiwsp.com
> ```
> 
> is enough to block all LG ads and recommendations on any region I guess

PiHole doesn't read regex in adlists. It needs to be entered manually in the regex column. I created this as a list so it could be easily imported and used by anyone who need it.

If you want to create a different file for another region, feel free to open another PR.

**Pull request closed without merging**
